plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
}
version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
        content { includeGroup "thedarkcolour" }
    }
    maven { url = uri("https://maven.shedaniel.me/") }
    maven {
        name = 'Xander Maven'
        url = 'https://maven.isxander.dev/releases/'
    }
    maven {
        name = "Gegy"
        url = uri("https://maven.gegy.dev/releases")
    }
    maven {
        name = "FabricMC"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "TerraBlender"
        url = "https://maven.blamejared.com"
    }
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)
kotlin.jvmToolchain(25)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named("jar", Jar).configure {
    from(sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def mappingsAttribute = Attribute.of("net.minecraft.mappings", String)

configurations {
    localRuntime
    runtimeClasspath.extendsFrom(localRuntime)
}

dependencies {
    attributesSchema {
        attribute(mappingsAttribute)
    }
    implementation 'thedarkcolour:kotlinforforge-neoforge:6.2.0'
    compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    runtimeOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    compileOnly "com.github.glitchfiend:TerraBlender-neoforge:${project.terrablender_version}"
    runtimeOnly "com.github.glitchfiend:TerraBlender-neoforge:${project.terrablender_version}"
    compileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:${project.lamb_dynamic_version}") {
        attributes {
            attribute(mappingsAttribute, "mojmap")
        }
    }
    add('localRuntime', "dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${project.lamb_dynamic_version}") {
        attributes {
            attribute(mappingsAttribute, "mojmap")
        }
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}